name: Build_development

on:
  workflow_dispatch:      # Start a workflow
  push:
    branches: development

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:

  base-images:
    runs-on: ubuntu-latest
    if: github.repository == 'ortegafernando/Tasmota'
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - tasmota

    steps:
      - uses: actions/checkout@v6
        with:
          ref: development
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: false
      - name: Install dependencies
        run: |
          uv pip install --system pioarduino==6.2.0
      - name: Add SHA to footer
        run: |
          COMMIT_SHA_LONG=$(git rev-parse --short HEAD || echo "")
          SHA=${COMMIT_SHA_LONG::7}
          sed -i -e "s/TASMOTA_SHA_SHORT/TASMOTA_SHA_SHORT $SHA-/g" ./tasmota/include/tasmota_version.h
      - name: Run PlatformIO
        env:
          PYTHONIOENCODING: utf-8
          PYTHONUTF8: '1'
        run: platformio run -e ${{ matrix.variant }}
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.variant }}
          path: ./build_output


  Start_final_copy:
    needs: [base-images]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
    - name: Dispatch workflow in arendst/Tasmota-firmware
      run: |
        gh api repos/arendst/Tasmota-firmware/actions/workflows/fetch_deploy.yml/dispatches \
          --method POST \
          -f ref='gh_actions'
